#!/usr/bin/env bash
#djaskdak
s=1 
while [ $s -le 100 ];
do 
  if (( s % 3 == 0 && s % 5 == 0 )) ; then
     echo "FizzBuzz"
  elif  (( s % 3 == 0 )); then
    echo "Fizz" 
  elif (( s % 5 == 0 )); then
    echo "Buzz"
  else 
     echo $s
  fi 
  ((s++))
done
