#!/usr/bin/env bash
#using IFS in loop  via read
while IFS=: read -r USERNAME PASSWORD USER ID GROUP_ID _ HOME_DIRECTORY COMMAND/SHELL ; 
do
  echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND/SHELL. $USER ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER ID INFO"
done < /etc/passwd
