#!/usr/bin/env bash
#djsaldka
c=1
while [ $c -lt 20 ] 
do 
 echo "$c"
 ((c++))
case $c in
     5)
     echo "bad luck from China"
     ;;
     10)
     echo "bad luck from Japan"
     ;;
     18)
     echo "bad luck from Italy"
     ;;
esac
done
