#!/usr/bin/env bash
# awk
for pid in /proc/[0-9]*; do
     if [[ -f "$pid/comm" ]]; then
        pname=$(<"$pid/comm")
     if [[ "$pname" == *bash* ]]; then
           echo "${pid##*/} $pname"
     fi
     fi
done
