#!/usr/bin/env bash
# using signals for interruption
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Проверяем, нашли ли процесс
if [[ -n "$pid" ]]; then
    kill "$pid"
    echo "Process 4-to_infinity_and_beyond (PID $pid) stopped."
else
    echo "Process 4-to_infinity_and_beyond not found."
fi
